### ISSUE TITLE
Unexpected keyword argument 'n' in function call

### ISSUE THREAD

**Issue by codeassassin007** [2018kguo/RobinhoodBot#18]
On lines 177 and 178, I have errors for the integer 'n' being unexpected when trying to run the script:

sma1 = ta.volatility.bollinger_mavg(price, n=int(n1), fillna=False)
sma2 = ta.volatility.bollinger_mavg(price, n=int(n2), fillna=False)

Below is what I receive from the console output:

_sma1 = ta.volatility.bollinger_mavg(price, n=int(n1), fillna=False)
TypeError: bollinger_mavg() got an unexpected keyword argument 'n'_

Any help would be greatly appreciated.

Thanks!

**Comment by 2018kguo** [comment]
I think you have an updated version of the "ta" module installed, and they changed the name of the parameter. Try changing n to window (you can see the new function header about halfway down the page here [https://technical-analysis-library-in-python.readthedocs.io/en/latest/ta.html#momentum-indicators](url) )

**Comment by codeassassin007** [comment]
This was great! That seemed to fix it. It didn't pull back any data, but I just assumed the stocks watched are not meeting the criteria to show up. Below is an output of what I received:

_----- Scanning watchlist for stocks to buy -----

robinhoodbot\main.py:166: FutureWarning: Units 'M', 'Y' and 'y' do not represent unambiguous timedelta values and will be removed in a future version
  if(direction == "above" and not five_year_check(stockTicker)):
----- Scan over -----_

Just wanted to make sure this would be expected if no stocks met the proposed strategy. Thanks again for the prompt response!

**Comment by 2018kguo** [comment]
Yeah, that looks normal

**Comment by codeassassin007** [comment]
Thanks. Closing issue.
