### ISSUE TITLE
NameError: name 'bollinger_mavg' is not defined

### ISSUE THREAD

**Issue by jdservice42** [2018kguo/RobinhoodBot#4]
My portfolio and watchlist are displayed and then I get this.

----- Scanning portfolio for stocks to sell -----

Traceback (most recent call last):
  File "main.py", line 258, in <module>
    scan_stocks()
  File "main.py", line 240, in scan_stocks
    cross = golden_cross(symbol, n1=50, n2=200, days=30, direction="below")
  File "main.py", line 170, in golden_cross
    sma1 = bollinger_mavg(price, n=int(n1), fillna=False)
NameError: name 'bollinger_mavg' is not defined
jdubb@Latitude-D630:~/RobinhoodBot/robinhoodbot$

What could this be?

**Comment by shafcodes** [comment]
I am assuming the implementation of Bollinger Moving Averages are missing from the code provided. You can either write your own definition to implement it or wait for the authors to provide the code for it.

Here is a repo i found that might help you understand what Bollinger moving/rolling averages are -

[https://github.com/umeshpalai/Rolling-Mean-Bollingerbands/blob/master/Rolling%20Mean%20%26%20Standard%20Deviation.ipynb](Umesh's repo)
